<a href="https://colab.research.google.com/github/tongtiger/KUanwjrrlrP/blob/master/kaggle/house_price/preprocessing_20_8_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
train = pd.read_csv("/content/drive/Shared drives/Kaggle/house_prices/data/train.csv")
train = pd.DataFrame(train)

test = pd.read_csv("/content/drive/Shared drives/Kaggle/house_prices/data/test.csv")
test = pd.DataFrame(test)

In [3]:
test_nullcolumn = []

for column in test.columns:
  for data in test[column].isnull():
    if data == True:
      if column not in test_nullcolumn:
        test_nullcolumn.append(column)

In [4]:
train_nullcolumn = {}

for column in train.columns:
  for data in train[column].isnull():
    if data == True:
      if column not in train_nullcolumn:
        train_nullcolumn[column] = 1
      else:
        train_nullcolumn[column] += 1

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [14]:
dtype = {'int64': [], 'float64': [], 'object' : []}

for column in train.columns:
  if train[column].dtype == 'object':
    dtype['object'].append(column)
  elif train[column].dtype == 'int64':
    dtype['int64'].append(column)
  else:
    dtype['float64'].append(column)

In [15]:
dtype

{'float64': ['LotFrontage', 'MasVnrArea', 'GarageYrBlt'],
 'int64': ['Id',
  'MSSubClass',
  'LotArea',
  'OverallQual',
  'OverallCond',
  'YearBuilt',
  'YearRemodAdd',
  'BsmtFinSF1',
  'BsmtFinSF2',
  'BsmtUnfSF',
  'TotalBsmtSF',
  '1stFlrSF',
  '2ndFlrSF',
  'LowQualFinSF',
  'GrLivArea',
  'BsmtFullBath',
  'BsmtHalfBath',
  'FullBath',
  'HalfBath',
  'BedroomAbvGr',
  'KitchenAbvGr',
  'TotRmsAbvGrd',
  'Fireplaces',
  'GarageCars',
  'GarageArea',
  'WoodDeckSF',
  'OpenPorchSF',
  'EnclosedPorch',
  '3SsnPorch',
  'ScreenPorch',
  'PoolArea',
  'MiscVal',
  'MoSold',
  'YrSold',
  'SalePrice'],
 'object': ['MSZoning',
  'Street',
  'Alley',
  'LotShape',
  'LandContour',
  'Utilities',
  'LotConfig',
  'LandSlope',
  'Neighborhood',
  'Condition1',
  'Condition2',
  'BldgType',
  'HouseStyle',
  'RoofStyle',
  'RoofMatl',
  'Exterior1st',
  'Exterior2nd',
  'MasVnrType',
  'ExterQual',
  'ExterCond',
  'Foundation',
  'BsmtQual',
  'BsmtCond',
  'BsmtExposure',
  'BsmtFinType1',
  'BsmtFinType2',
  'Heating',
  'HeatingQC',
  'CentralAir',
  'Electrical',
  'KitchenQual',
  'Functional',
  'FireplaceQu',
  'GarageType',
  'GarageFinish',
  'GarageQual',
  'GarageCond',
  'PavedDrive',
  'PoolQC',
  'Fence',
  'MiscFeature',
  'SaleType',
  'SaleCondition']}

In [16]:
max_values = {}

In [17]:
object_values = {}

In [18]:
for column in train.columns:
  if column == 'SalePrice' or column == 'Id':
    pass
  elif column not in dtype['object']:
    max_value = max(train[column])
    max_values[column] = max_value
    train[column] = train[column]/max_value
  else:
    k = 1
    for data in train[column]:
      if data not in object_values:
        object_values[data] = k
        k += 1
      else:
        pass

In [19]:
max_values

{'1stFlrSF': 4692,
 '2ndFlrSF': 2065,
 '3SsnPorch': 508,
 'BedroomAbvGr': 8,
 'BsmtFinSF1': 5644,
 'BsmtFinSF2': 1474,
 'BsmtFullBath': 3,
 'BsmtHalfBath': 2,
 'BsmtUnfSF': 2336,
 'EnclosedPorch': 552,
 'Fireplaces': 3,
 'FullBath': 3,
 'GarageArea': 1418,
 'GarageCars': 4,
 'GarageYrBlt': 2010.0,
 'GrLivArea': 5642,
 'HalfBath': 2,
 'KitchenAbvGr': 3,
 'LotArea': 215245,
 'LotFrontage': 313.0,
 'LowQualFinSF': 572,
 'MSSubClass': 190,
 'MasVnrArea': 1600.0,
 'MiscVal': 15500,
 'MoSold': 12,
 'OpenPorchSF': 547,
 'OverallCond': 9,
 'OverallQual': 10,
 'PoolArea': 738,
 'ScreenPorch': 480,
 'TotRmsAbvGrd': 14,
 'TotalBsmtSF': 6110,
 'WoodDeckSF': 857,
 'YearBuilt': 2010,
 'YearRemodAdd': 2010,
 'YrSold': 2010}

In [20]:
object_values

{'1.5Fin': 3,
 '1.5Unf': 4,
 '1Fam': 1,
 '1Story': 2,
 '2.5Fin': 8,
 '2.5Unf': 7,
 '2Story': 1,
 '2Types': 6,
 '2fmCon': 2,
 'ALQ': 2,
 'Abnorml': 2,
 'AdjLand': 4,
 'AllPub': 1,
 'Alloca': 5,
 'Artery': 4,
 'AsbShng': 9,
 'AsphShn': 12,
 'Attchd': 1,
 'Av': 3,
 'BLQ': 5,
 'Basment': 5,
 'Blmngtn': 22,
 'Blueste': 25,
 'Bnk': 2,
 'BrDale': 23,
 'Brk Cmn': 3,
 'BrkCmn': 2,
 'BrkComm': 11,
 'BrkFace': 5,
 'BrkSide': 9,
 'BrkTil': 2,
 'BuiltIn': 3,
 'C (all)': 3,
 'CBlock': 15,
 'COD': 3,
 'CWD': 6,
 'CarPort': 4,
 'CemntBd': 7,
 'ClearCr': 20,
 'ClyTile': 8,
 'CmentBd': 2,
 'CollgCr': 1,
 'CompShg': 1,
 'Con': 8,
 'ConLD': 4,
 'ConLI': 5,
 'ConLw': 7,
 'Corner': 3,
 'Crawfor': 3,
 'CulDSac': 4,
 'Detchd': 2,
 'Duplex': 3,
 'Edwards': 16,
 'Ex': 3,
 'FR2': 2,
 'FR3': 5,
 'FV': 4,
 'Fa': 4,
 'Family': 6,
 'Feedr': 2,
 'Fin': 2,
 'Flat': 5,
 'Floor': 6,
 'FuseA': 3,
 'FuseF': 2,
 'FuseP': 4,
 'GLQ': 1,
 'Gable': 1,
 'Gambrel': 3,
 'Gar2': 1,
 'GasA': 1,
 'GasW': 2,
 'Gd': 1,
 'GdPrv': 3,
 'GdWo': 2,
 'Gilbert': 18,
 'Grav': 3,
 'Grvl': 2,
 'Gtl': 1,
 'HLS': 4,
 'HdBoard': 4,
 'Hip': 2,
 'IDOTRR': 14,
 'IR1': 2,
 'IR2': 3,
 'IR3': 4,
 'ImStucc': 14,
 'Inside': 1,
 'Low': 3,
 'Lvl': 1,
 'LwQ': 6,
 'Maj1': 3,
 'Maj2': 5,
 'Mansard': 4,
 'MeadowV': 15,
 'Membran': 5,
 'Metal': 3,
 'MetalSd': 2,
 'Min1': 2,
 'Min2': 4,
 'Mitchel': 5,
 'Mix': 5,
 'Mn': 2,
 'MnPrv': 1,
 'MnWw': 4,
 'Mod': 2,
 'N': 2,
 'NAmes': 12,
 'NPkVill': 21,
 'NWAmes': 7,
 'New': 2,
 'No': 1,
 'NoRidge': 4,
 'NoSeWa': 2,
 'None': 1,
 'Norm': 1,
 'Normal': 1,
 'NridgHt': 11,
 'OldTown': 8,
 'Oth': 9,
 'OthW': 5,
 'Other': 4,
 'Othr': 2,
 'P': 1,
 'PConc': 1,
 'Partial': 3,
 'Pave': 1,
 'Plywood': 8,
 'Po': 1,
 'PosA': 8,
 'PosN': 3,
 'RFn': 1,
 'RH': 5,
 'RL': 1,
 'RM': 2,
 'RRAe': 5,
 'RRAn': 7,
 'RRNe': 9,
 'RRNn': 6,
 'Rec': 4,
 'Reg': 1,
 'Roll': 7,
 'SBrkr': 1,
 'SFoyer': 5,
 'SLvl': 6,
 'SWISU': 24,
 'Sawyer': 10,
 'SawyerW': 13,
 'Sev': 3,
 'Shed': 6,
 'Slab': 4,
 'Somerst': 6,
 'Stone': 13,
 'StoneBr': 19,
 'Stucco': 10,
 'TA': 2,
 'Tar&Grv': 6,
 'TenC': 3,
 'Timber': 17,
 'Twnhs': 5,
 'TwnhsE': 4,
 'Typ': 1,
 'Unf': 3,
 'Veenker': 2,
 'VinylSd': 1,
 'WD': 1,
 'Wall': 4,
 'Wd Sdng': 3,
 'Wd Shng': 1,
 'WdShake': 4,
 'WdShing': 6,
 'WdShngl': 2,
 'Wood': 3,
 'Y': 1,
 nan: 1}

In [21]:
average_value = {}

In [22]:
for column in train.columns:
  if column not in dtype['object']:
    average = train[column].mean
    train[column] = train[column].fillna(average)
    average_value[column] = average
  else:
    pass

In [23]:
average_value

{'1stFlrSF': <bound method Series.mean of 0       0.182438
 1       0.268968
 2       0.196078
 3       0.204817
 4       0.244032
           ...
 1455    0.203112
 1456    0.441816
 1457    0.253197
 1458    0.229753
 1459    0.267690
 Name: 1stFlrSF, Length: 1460, dtype: float64>,
 '2ndFlrSF': <bound method Series.mean of 0       0.413559
 1       0.000000
 2       0.419370
 3       0.366102
 4       0.509927
           ...
 1455    0.336077
 1456    0.000000
 1457    0.557869
 1458    0.000000
 1459    0.000000
 Name: 2ndFlrSF, Length: 1460, dtype: float64>,
 '3SsnPorch': <bound method Series.mean of 0       0.0
 1       0.0
 2       0.0
 3       0.0
 4       0.0
        ...
 1455    0.0
 1456    0.0
 1457    0.0
 1458    0.0
 1459    0.0
 Name: 3SsnPorch, Length: 1460, dtype: float64>,
 'BedroomAbvGr': <bound method Series.mean of 0       0.375
 1       0.375
 2       0.375
 3       0.375
 4       0.500
         ...
 1455    0.375
 1456    0.375
 1457    0.500
 1458    0.250
 1459    0.375
 Name: BedroomAbvGr, Length: 1460, dtype: float64>,
 'BsmtFinSF1': <bound method Series.mean of 0       0.125089
 1       0.173281
 2       0.086109
 3       0.038271
 4       0.116052
           ...
 1455    0.000000
 1456    0.139972
 1457    0.048724
 1458    0.008682
 1459    0.147059
 Name: BsmtFinSF1, Length: 1460, dtype: float64>,
 'BsmtFinSF2': <bound method Series.mean of 0       0.000000
 1       0.000000
 2       0.000000
 3       0.000000
 4       0.000000
           ...
 1455    0.000000
 1456    0.110583
 1457    0.000000
 1458    0.698100
 1459    0.196744
 Name: BsmtFinSF2, Length: 1460, dtype: float64>,
 'BsmtFullBath': <bound method Series.mean of 0       0.333333
 1       0.000000
 2       0.333333
 3       0.333333
 4       0.333333
           ...
 1455    0.000000
 1456    0.333333
 1457    0.000000
 1458    0.333333
 1459    0.333333
 Name: BsmtFullBath, Length: 1460, dtype: float64>,
 'BsmtHalfBath': <bound method Series.mean of 0       0.0
 1       0.5
 2       0.0
 3       0.0
 4       0.0
        ...
 1455    0.0
 1456    0.0
 1457    0.0
 1458    0.0
 1459    0.0
 Name: BsmtHalfBath, Length: 1460, dtype: float64>,
 'BsmtUnfSF': <bound method Series.mean of 0       0.064212
 1       0.121575
 2       0.185788
 3       0.231164
 4       0.209760
           ...
 1455    0.407962
 1456    0.252140
 1457    0.375428
 1458    0.000000
 1459    0.058219
 Name: BsmtUnfSF, Length: 1460, dtype: float64>,
 'EnclosedPorch': <bound method Series.mean of 0       0.000000
 1       0.000000
 2       0.000000
 3       0.492754
 4       0.000000
           ...
 1455    0.000000
 1456    0.000000
 1457    0.000000
 1458    0.202899
 1459    0.000000
 Name: EnclosedPorch, Length: 1460, dtype: float64>,
 'Fireplaces': <bound method Series.mean of 0       0.000000
 1       0.333333
 2       0.333333
 3       0.333333
 4       0.333333
           ...
 1455    0.333333
 1456    0.666667
 1457    0.666667
 1458    0.000000
 1459    0.000000
 Name: Fireplaces, Length: 1460, dtype: float64>,
 'FullBath': <bound method Series.mean of 0       0.666667
 1       0.666667
 2       0.666667
 3       0.333333
 4       0.666667
           ...
 1455    0.666667
 1456    0.666667
 1457    0.666667
 1458    0.333333
 1459    0.333333
 Name: FullBath, Length: 1460, dtype: float64>,
 'GarageArea': <bound method Series.mean of 0       0.386460
 1       0.324401
 2       0.428773
 3       0.452750
 4       0.589563
           ...
 1455    0.324401
 1456    0.352609
 1457    0.177715
 1458    0.169252
 1459    0.194640
 Name: GarageArea, Length: 1460, dtype: float64>,
 'GarageCars': <bound method Series.mean of 0       0.50
 1       0.50
 2       0.50
 3       0.75
 4       0.75
         ...
 1455    0.50
 1456    0.50
 1457    0.25
 1458    0.25
 1459    0.25
 Name: GarageCars, Length: 1460, dtype: float64>,
 'GarageYrBlt': <bound method Series.mean of 0       0.996517
 1       0.983085
 2       0.995522
 3       0.994030
 4       0.995025
           ...
 1455    0.994527
 1456    0.984080
 1457    0.965672
 1458    0.970149
 1459    0.977612
 Name: GarageYrBlt, Length: 1460, dtype: float64>,
 'GrLivArea': <bound method Series.mean of 0       0.303084
 1       0.223680
 2       0.316554
 3       0.304325
 4       0.389578
           ...
 1455    0.291918
 1456    0.367423
 1457    0.414747
 1458    0.191067
 1459    0.222616
 Name: GrLivArea, Length: 1460, dtype: float64>,
 'HalfBath': <bound method Series.mean of 0       0.5
 1       0.0
 2       0.5
 3       0.0
 4       0.5
        ...
 1455    0.5
 1456    0.0
 1457    0.0
 1458    0.0
 1459    0.5
 Name: HalfBath, Length: 1460, dtype: float64>,
 'Id': <bound method Series.mean of 0          1
 1          2
 2          3
 3          4
 4          5
         ...
 1455    1456
 1456    1457
 1457    1458
 1458    1459
 1459    1460
 Name: Id, Length: 1460, dtype: int64>,
 'KitchenAbvGr': <bound method Series.mean of 0       0.333333
 1       0.333333
 2       0.333333
 3       0.333333
 4       0.333333
           ...
 1455    0.333333
 1456    0.333333
 1457    0.333333
 1458    0.333333
 1459    0.333333
 Name: KitchenAbvGr, Length: 1460, dtype: float64>,
 'LotArea': <bound method Series.mean of 0       0.039258
 1       0.044600
 2       0.052266
 3       0.044368
 4       0.066250
           ...
 1455    0.036781
 1456    0.061209
 1457    0.042008
 1458    0.045144
 1459    0.046166
 Name: LotArea, Length: 1460, dtype: float64>,
 'LotFrontage': <bound method Series.mean of 0       0.207668
 1       0.255591
 2       0.217252
 3       0.191693
 4       0.268371
           ...
 1455    0.198083
 1456    0.271565
 1457    0.210863
 1458    0.217252
 1459    0.239617
 Name: LotFrontage, Length: 1460, dtype: float64>,
 'LowQualFinSF': <bound method Series.mean of 0       0.0
 1       0.0
 2       0.0
 3       0.0
 4       0.0
        ...
 1455    0.0
 1456    0.0
 1457    0.0
 1458    0.0
 1459    0.0
 Name: LowQualFinSF, Length: 1460, dtype: float64>,
 'MSSubClass': <bound method Series.mean of 0       0.315789
 1       0.105263
 2       0.315789
 3       0.368421
 4       0.315789
           ...
 1455    0.315789
 1456    0.105263
 1457    0.368421
 1458    0.105263
 1459    0.105263
 Name: MSSubClass, Length: 1460, dtype: float64>,
 'MasVnrArea': <bound method Series.mean of 0       0.122500
 1       0.000000
 2       0.101250
 3       0.000000
 4       0.218750
           ...
 1455    0.000000
 1456    0.074375
 1457    0.000000
 1458    0.000000
 1459    0.000000
 Name: MasVnrArea, Length: 1460, dtype: float64>,
 'MiscVal': <bound method Series.mean of 0       0.00000
 1       0.00000
 2       0.00000
 3       0.00000
 4       0.00000
          ...
 1455    0.00000
 1456    0.00000
 1457    0.16129
 1458    0.00000
 1459    0.00000
 Name: MiscVal, Length: 1460, dtype: float64>,
 'MoSold': <bound method Series.mean of 0       0.166667
 1       0.416667
 2       0.750000
 3       0.166667
 4       1.000000
           ...
 1455    0.666667
 1456    0.166667
 1457    0.416667
 1458    0.333333
 1459    0.500000
 Name: MoSold, Length: 1460, dtype: float64>,
 'OpenPorchSF': <bound method Series.mean of 0       0.111517
 1       0.000000
 2       0.076782
 3       0.063985
 4       0.153565
           ...
 1455    0.073126
 1456    0.000000
 1457    0.109689
 1458    0.000000
 1459    0.124314
 Name: OpenPorchSF, Length: 1460, dtype: float64>,
 'OverallCond': <bound method Series.mean of 0       0.555556
 1       0.888889
 2       0.555556
 3       0.555556
 4       0.555556
           ...
 1455    0.555556
 1456    0.666667
 1457    1.000000
 1458    0.666667
 1459    0.666667
 Name: OverallCond, Length: 1460, dtype: float64>,
 'OverallQual': <bound method Series.mean of 0       0.7
 1       0.6
 2       0.7
 3       0.7
 4       0.8
        ...
 1455    0.6
 1456    0.6
 1457    0.7
 1458    0.5
 1459    0.5
 Name: OverallQual, Length: 1460, dtype: float64>,
 'PoolArea': <bound method Series.mean of 0       0.0
 1       0.0
 2       0.0
 3       0.0
 4       0.0
        ...
 1455    0.0
 1456    0.0
 1457    0.0
 1458    0.0
 1459    0.0
 Name: PoolArea, Length: 1460, dtype: float64>,
 'SalePrice': <bound method Series.mean of 0       208500
 1       181500
 2       223500
 3       140000
 4       250000
          ...
 1455    175000
 1456    210000
 1457    266500
 1458    142125
 1459    147500
 Name: SalePrice, Length: 1460, dtype: int64>,
 'ScreenPorch': <bound method Series.mean of 0       0.0
 1       0.0
 2       0.0
 3       0.0
 4       0.0
        ...
 1455    0.0
 1456    0.0
 1457    0.0
 1458    0.0
 1459    0.0
 Name: ScreenPorch, Length: 1460, dtype: float64>,
 'TotRmsAbvGrd': <bound method Series.mean of 0       0.571429
 1       0.428571
 2       0.428571
 3       0.500000
 4       0.642857
           ...
 1455    0.500000
 1456    0.500000
 1457    0.642857
 1458    0.357143
 1459    0.428571
 Name: TotRmsAbvGrd, Length: 1460, dtype: float64>,
 'TotalBsmtSF': <bound method Series.mean of 0       0.140098
 1       0.206547
 2       0.150573
 3       0.123732
 4       0.187398
           ...
 1455    0.155974
 1456    0.252373
 1457    0.188543
 1458    0.176432
 1459    0.205565
 Name: TotalBsmtSF, Length: 1460, dtype: float64>,
 'WoodDeckSF': <bound method Series.mean of 0       0.000000
 1       0.347725
 2       0.000000
 3       0.000000
 4       0.224037
           ...
 1455    0.000000
 1456    0.407235
 1457    0.000000
 1458    0.427071
 1459    0.858810
 Name: WoodDeckSF, Length: 1460, dtype: float64>,
 'YearBuilt': <bound method Series.mean of 0       0.996517
 1       0.983085
 2       0.995522
 3       0.952736
 4       0.995025
           ...
 1455    0.994527
 1456    0.984080
 1457    0.965672
 1458    0.970149
 1459    0.977612
 Name: YearBuilt, Length: 1460, dtype: float64>,
 'YearRemodAdd': <bound method Series.mean of 0       0.996517
 1       0.983085
 2       0.996020
 3       0.980100
 4       0.995025
           ...
 1455    0.995025
 1456    0.989055
 1457    0.998010
 1458    0.993035
 1459    0.977612
 Name: YearRemodAdd, Length: 1460, dtype: float64>,
 'YrSold': <bound method Series.mean of 0       0.999005
 1       0.998507
 2       0.999005
 3       0.998010
 4       0.999005
           ...
 1455    0.998507
 1456    1.000000
 1457    1.000000
 1458    1.000000
 1459    0.999005
 Name: YrSold, Length: 1460, dtype: float64>}

In [24]:
for data in object_values:
  train.replace(to_replace=data, value = object_values[data], inplace=True)

train = train.fillna(0)

In [25]:
for column in train.columns:
  for data in train[column].isnull():
    if data == True:
      print(column)

In [26]:
train

        Id  MSSubClass  MSZoning  ... SaleType  SaleCondition  SalePrice
0        1    0.315789         1  ...        1              1     208500
1        2    0.105263         1  ...        1              1     181500
2        3    0.315789         1  ...        1              1     223500
3        4    0.368421         1  ...        1              2     140000
4        5    0.315789         1  ...        1              1     250000
...    ...         ...       ...  ...      ...            ...        ...
1455  1456    0.315789         1  ...        1              1     175000
1456  1457    0.105263         1  ...        1              1     210000
1457  1458    0.368421         1  ...        1              1     266500
1458  1459    0.105263         1  ...        1              1     142125
1459  1460    0.105263         1  ...        1              1     147500

[1460 rows x 81 columns]

In [29]:
train.to_csv("/content/drive/Shared drives/Kaggle/house_prices/data/train_data_20_8_4.csv", index=False)

In [31]:
for column in test.columns:
  if column == 'SalePrice' or column == 'Id':
    pass
  elif column not in dtype['object']:
    test[column] = test[column]/max_values[column]
  else:
    pass

In [32]:
for column in test.columns:
  if column not in dtype['object']:
    test[column] = test[column].fillna(average_value[column])
  else:
    pass

In [33]:
for data in object_values:
  test.replace(to_replace=data, value = object_values[data], inplace=True)

test = test.fillna(0)

In [34]:
for column in test.columns:
  for data in test[column].isnull():
    if data == True:
      print(column)

In [35]:
test

        Id  MSSubClass  MSZoning  ...   YrSold  SaleType  SaleCondition
0     1461    0.105263       5.0  ...  1.00000         1              1
1     1462    0.105263       1.0  ...  1.00000         1              1
2     1463    0.315789       1.0  ...  1.00000         1              1
3     1464    0.315789       1.0  ...  1.00000         1              1
4     1465    0.631579       1.0  ...  1.00000         1              1
...    ...         ...       ...  ...      ...       ...            ...
1454  2915    0.842105       2.0  ...  0.99801         1              1
1455  2916    0.842105       2.0  ...  0.99801         1              2
1456  2917    0.105263       1.0  ...  0.99801         1              2
1457  2918    0.447368       1.0  ...  0.99801         1              1
1458  2919    0.315789       1.0  ...  0.99801         1              1

[1459 rows x 80 columns]

In [36]:
test.to_csv("/content/drive/Shared drives/Kaggle/house_prices/data/test_data_20_8_4.csv", index=False)